### ISSUE TITLE
Flux capacitor is broken

### ISSUE THREAD

**Issue by kwbeam** [nsidc/test-repo#3] opened 2021-04-21 19:08 UTC
When I try to use this software, the flux capacitor appears to be offline. I did a little debugging and I think the quantum flux tubes may have undergone spontaneous vacuum decay, resulting in spurious virtual particle pair creation, and subsequent kablooey!

**Comment by kbeamnsidc** [comment] 2021-04-21 19:10
Hi Kevin, this is Kevin. Have you recharged the flux capacitor at 1.21 GW? That usually does it for me. Otherwise, try rebooting it.

**Comment by kwbeam** [comment] 2021-04-21 19:12
Hi Kevin. Yes, I charged it at 1.21 GW and other than a little smoke and heat, nothing happened. The flux capacitor is still broken. I just tried rebooting it and still nothing. What else could I try? Can you assign this ticket to someone on your team who actually knows things?

**Comment by kbeamnsidc** [comment] 2021-04-21 19:13
Um, sure. @chris-torrence can you help with this flux capacitor problem?

**Comment by chris-torrence** [comment] 2021-04-21 19:32
Well, I think the problem is that you hooked it into the oscillating overthruster. Yoyodyne never tested that scenario.

**Comment by chris-torrence** [comment] 2021-04-21 19:33
Closing as USER ERROR. Do not plug flux capacitor into oscillating overthruster. It says that in the manual on p. 897.

**Closed by chris-torrence** 2021-04-21 19:33 UTC
Labels: help wanted

**Comment by kwbeam** [comment] 2021-04-21 19:37
🤦🏽 Gah! You're right! Sorry about that, section 18.3.2.97 of the manual was the *one* section I didn't read. To be fair, the section was titled "Notes on seldom-encountered vacuum collapse scenarios when integrating a flux capacitor with a wormhole, while simultaneously executing a time-slant maneuver which very infrequently engages the overthruster and puts it into oscillation." Not exactly a riveting read, I have to say.
